# permissions for end users to view volumebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: volume-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: volumebackup-viewer-role
rules:
- apiGroups:
  - backup.infra.dev
  resources:
  - volumebackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.infra.dev
  resources:
  - volumebackups/status
  verbs:
  - get
