# permissions for end users to edit volumebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: volume-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: volumebackup-editor-role
rules:
- apiGroups:
  - backup.k8s.io
  resources:
  - volumebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.k8s.io
  resources:
  - volumebackups/status
  verbs:
  - get
