apiVersion: backup.infra.dev/v1
kind: VolumeSnapshot
metadata:
  labels:
    app.kubernetes.io/name: volume-backup-operator
    app.kubernetes.io/managed-by: kustomize
  name: volumesnapshot-sample
  namespace: "ns-two"
spec:
  pvcselectorlabel: "testing-myvolumesnapshot-crd"
