apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testing-pvc-1
  namespace: ns-two
  labels:
    pvcselectorlabel: "testing-myvolumesnapshot-crd"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: csi-hostpath-sc
